all:
	(cd host && make)
	(cd host-mini && make)
	(cd host-parallel && make)
	(cd host-arduino && make)
	(cd host-sdl && make)

clean:
	(cd host && make clean)
	(cd host-mini && make clean)
	(cd host-parallel && make clean)
	(cd host-arduino && make clean)
	(cd host-sdl && make clean)

